# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  image_entry: images
  public_output_path: packs
  source_path: src
  source_entry_path: packs
  stylesheets_entry: stylesheets

  extensions:
    - .erb
    - .js
    - .jsx
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

  dev_server:
    host: 0.0.0.0
    port: 8080
    https: false

test:
  <<: *default

  public_output_path: packs-test

staging:
  <<: *default

production:
  <<: *default
